// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyu9AFlcGmVqS4z8X-f-hvboOKSevuXo',
    appId: '1:373498621978:android:3d55e54d42e2c234aee1a3',
    messagingSenderId: '373498621978',
    projectId: 'monthly-expense-tracker-b06e6',
    storageBucket: 'monthly-expense-tracker-b06e6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLW4xh9yCJc4XVHXK7CEZ8QZaXoJ8x24',
    appId: '1:373498621978:ios:928d2fd177f181f7aee1a3',
    messagingSenderId: '373498621978',
    projectId: 'monthly-expense-tracker-b06e6',
    storageBucket: 'monthly-expense-tracker-b06e6.firebasestorage.app',
    iosBundleId: 'com.example.myExpensesModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAleESsIGSELEUcVrCSDJJAY40qnidpE04',
    appId: '1:373498621978:web:e42367cc00c68d2eaee1a3',
    messagingSenderId: '373498621978',
    projectId: 'monthly-expense-tracker-b06e6',
    authDomain: 'monthly-expense-tracker-b06e6.firebaseapp.com',
    storageBucket: 'monthly-expense-tracker-b06e6.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleESsIGSELEUcVrCSDJJAY40qnidpE04',
    appId: '1:373498621978:web:e42367cc00c68d2eaee1a3',
    messagingSenderId: '373498621978',
    projectId: 'monthly-expense-tracker-b06e6',
    authDomain: 'monthly-expense-tracker-b06e6.firebaseapp.com',
    storageBucket: 'monthly-expense-tracker-b06e6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACLW4xh9yCJc4XVHXK7CEZ8QZaXoJ8x24',
    appId: '1:373498621978:ios:928d2fd177f181f7aee1a3',
    messagingSenderId: '373498621978',
    projectId: 'monthly-expense-tracker-b06e6',
    storageBucket: 'monthly-expense-tracker-b06e6.firebasestorage.app',
    iosBundleId: 'com.example.myExpensesModule',
  );
}
